"""change patient db type'


Revision ID: 7ef0a8ae882a
Revises: b4dce5601f41
Create Date: 2022-10-08 19:00:48.698394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ef0a8ae882a'
down_revision = 'b4dce5601f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('date_of_birth', sa.String(length=64), nullable=True))
    op.drop_column('patient', 'dob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('dob', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('patient', 'date_of_birth')
    # ### end Alembic commands ###
