"""update patients

Revision ID: b4dce5601f41
Revises: d8990642ff3a
Create Date: 2022-10-08 18:10:48.919304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dce5601f41'
down_revision = 'd8990642ff3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'status')
    op.drop_column('patient', 'image_id')
    # ### end Alembic commands ###
